created Vision
Spikes-2212-Programming-Guild/ChargedUp2023 pull request #4
Opened 2023-01-19 16:56 UTC by AmitBrunicki

2023-01-19 19:18 UTC, Spikes-2212 requested changes

2023-01-19 19:18 UTC, Spikes-2212 commented on src/main/java/frc/robot/subsystems/Vision.java
> +    public static final String CAMERA_NAME = "photoncamera";
PHOTON_VISION_CAMERA_NAME

2023-01-19 19:18 UTC, Spikes-2212 commented on src/main/java/frc/robot/subsystems/Vision.java
> +    private static Vision instance;
private static comes after public static

2023-01-19 19:18 UTC, Spikes-2212 commented on src/main/java/frc/robot/subsystems/Vision.java
> +    public static final int PIPELINE_CONE_INDEX = 1;
index starts at 0

2023-01-19 19:18 UTC, Spikes-2212 commented on src/main/java/frc/robot/subsystems/Vision.java
> +    public static final int PIPELINE_RETROREFLECTIVE_INDEX = 1;
index starts at 0

2023-01-19 19:18 UTC, Spikes-2212 commented on src/main/java/frc/robot/subsystems/Vision.java
> +        return limelight.isOnTarget();
should use `limelight.hasTarget()`

2023-01-19 19:18 UTC, Spikes-2212 commented on src/main/java/frc/robot/subsystems/Vision.java
> +    public boolean limelightIsOnTarget(){
`limelightHasTarget`

2023-01-19 19:18 UTC, Spikes-2212 commented on src/main/java/frc/robot/subsystems/Vision.java
> +    public boolean photonvisionIsOnTarget(){
no need for this

2023-01-19 19:18 UTC, Spikes-2212 commented on vendordeps/photonlib.json
> +}
add blank line at the end of the file

2023-01-19 19:18 UTC, Spikes-2212 commented on src/main/java/frc/robot/subsystems/Vision.java
> +    public static final int PIPELINE_APRILTAG_INDEX = 2;
ditto

2023-01-19 19:18 UTC, Spikes-2212 commented on src/main/java/frc/robot/subsystems/Vision.java
> +    public static final int PIPELINE_CUBE_INDEX = 2;
ditto

2023-01-19 19:37 UTC, AmitBrunicki commented
now it is perfect

2023-01-20 15:56 UTC, OfriRosenbaum requested changes

2023-01-20 15:56 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Vision.java
> +    public static final String PHOTON_VISION_CAMERA_NAME = "photoncamera";
should be `photonvision`

2023-01-25 13:33 UTC, Spikes-2212 requested changes
Add a method that returns that april tag id from the limelight and a method that returns the pose3d from the limelight

2023-01-25 13:35 UTC, Spikes-2212 requested changes

2023-01-25 13:35 UTC, Spikes-2212 commented on src/main/java/frc/robot/subsystems/Vision.java
> +        super("vision");
get the namespaceName as a parameter and give it when you construct the instance

2023-02-17 09:08 UTC, closed without merging