created Arm
Spikes-2212-Programming-Guild/ChargedUp2023 pull request #5
Opened 2023-01-25 16:43 UTC by Spikes-2212

2023-01-27 10:01 UTC, OfriRosenbaum requested changes

2023-01-27 10:01 UTC, OfriRosenbaum commented on src/main/java/frc/robot/RobotMap.java
> +        int ARM_SECOND_JOINT_SPARKMAX_1 = -1;
second joint has only one sparkmax, it doesn't need any indexing

2023-01-27 10:01 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/ArmFirstJoint.java
> +        namespace.putNumber("first joint encoder position", this::getEncoderPosition);
no need to write first joint. this is already in the first joint namespace

2023-01-27 10:01 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/ArmFirstJoint.java
> +        this.trapezoidProfileSettings = new TrapezoidProfileSettings(trapezoidVelocity, trapezoidAcceleration);
add a call to configureDashboard in the end of the constructor

2023-01-27 10:01 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/ArmSecondJoint.java
> +    private final com.spikes2212.control.PIDSettings PIDSettings;
just write PIDSettings, don't write the whole package name

2023-01-27 10:01 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/ArmSecondJoint.java
> +    public static ArmSecondJoint getInstance() {
move this above the constructor

2023-01-27 10:01 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/ArmSecondJoint.java
> +        namespace.putNumber("second joint encoder position", this::getEncoderPosition);
no need to write second joint..

2023-01-27 10:01 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/ArmSecondJoint.java
> +        this.trapezoidProfileSettings = new TrapezoidProfileSettings(trapezoidVelocity, trapezoidAcceleration);
add a call to configureDashboard in the end of the constructor

2023-01-29 07:06 UTC, OfriRosenbaum requested changes

2023-01-29 07:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/ArmFirstJoint.java
> +
remove blank line

2023-01-29 07:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/RobotMap.java
> +        int ARM_FIRST_JOINT_SPARKMAX_1 = -1;
rename all of these to master and slaves accordingly

2023-01-29 07:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/ArmFirstJoint.java
> +        encoder.setPositionConversionFactor(DISTANCE_PER_PULSE);
call `setConversionRates()` instead

2023-01-29 07:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/ArmFirstJoint.java
> +    public void setConversionRates() {
rename to `setConversionFactors()`

2023-01-29 07:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/ArmSecondJoint.java
> +        encoder.setPositionConversionFactor(DISTANCE_PER_PULSE);
call `setConversionRates()` instead

2023-01-29 07:06 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/ArmSecondJoint.java
> +        slave.follow(master, false);
no need for this, slave already follows master (look in the super constructor)

2023-01-29 09:19 UTC, Yoel-Perman-Brilliant requested changes

2023-01-29 09:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/RobotMap.java
> +        int ARM_FIRST_JOINT_SPARKMAX_1 = -1;
change everything to master/slave

2023-01-29 09:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/ArmFirstJoint.java
> +import java.beans.Encoder;
![](https://media.tenor.com/eML-M9iCFIIAAAAd/huh-heh.gif)

2023-01-29 09:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/ArmFirstJoint.java
> +    private final RelativeEncoder encoder;
add `TODO check encoder type`

2023-01-29 09:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/ArmFirstJoint.java
> +    public double getEncoderPosition() {
A-III\a6

2023-01-29 09:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/ArmFirstJoint.java
> +    public void configureDashboard() {
ditto

2023-01-29 09:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/ArmFirstJoint.java
> +    public void configureLoop(PIDSettings PIDSettings, FeedForwardSettings feedForwardSettings,
How tf does this code compile with two `PIDSettings`

2023-01-29 09:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/ArmSecondJoint.java
> +    private final Namespace PIDNamespace = namespace.addChild("pid");
A-I\a1

2023-01-29 09:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/ArmSecondJoint.java
> +    private final RelativeEncoder encoder;
move below constants

2023-01-29 09:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/ArmFirstJoint.java
> +        this.encoder = master.getEncoder();
alternate/absolute encoder

2023-01-29 09:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/ArmFirstJoint.java
> +public class ArmFirstJoint extends SparkMaxGenericSubsystem {
Bad name

2023-01-29 09:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/ArmSecondJoint.java
> +public class ArmSecondJoint extends SparkMaxGenericSubsystem {
bad name

2023-01-29 09:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/ArmSecondJoint.java
> +    private final PIDSettings PIDSettings;
ditto

2023-01-29 09:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/ArmSecondJoint.java
> +    public double getEncoderPosition() {
A-III\a6

2023-01-29 09:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/ArmSecondJoint.java
> +    public void configureDashboard() {
ditto

2023-01-29 09:19 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/ArmSecondJoint.java
> +    public double getEncoderPosition() {
rename to `getPosition`

2023-02-04 08:32 UTC, Yoel-Perman-Brilliant requested changes

2023-02-04 08:32 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/MoveArm.java
> +        REST(0, 0), FLOOR(0, 0), DOUBLE_SUBSTATION(0, 0), BOTTOM(0, 0), CUBE_MID(0, 0),
this will be fun to calibrate

2023-02-04 08:32 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/MoveArm.java
> +                new MoveSmartMotorControllerSubsystemTrapezically(secondJoint,
remind me to talk to you about it, I worry that trapezim won't work

2023-02-04 08:32 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/ArmFirstJoint.java
> +        slave.follow(master, true);
unnecessary

2023-02-04 08:32 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/ArmFirstJoint.java
> +    public double getPosition() {
`getRelativePosition`

2023-02-04 08:44 UTC, Spikes-2212 commented on src/main/java/frc/robot/subsystems/ArmFirstJoint.java
> +        slave.follow(master, true);
No

2023-02-04 13:47 UTC, Yoel-Perman-Brilliant requested changes

2023-02-04 13:47 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/ArmFirstJoint.java
> +        absoluteEncoder.setDistancePerRotation(DISTANCE_PER_PULSE);
![image](https://user-images.githubusercontent.com/87820740/216770961-33b805f6-3bde-4774-8380-364fdb5eff21.png)

2023-02-04 13:47 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/ArmFirstJoint.java
> +    public void configureDashboard() {
add speed

2023-02-04 13:47 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/RobotMap.java
> +        int ARM_SECOND_JOINT_SPARKMAX_MASTER = -1;
why master if it's the only one?

2023-02-04 13:47 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/ArmSecondJoint.java
> +        absoluteEncoder.setDistancePerRotation(DISTANCE_PER_PULSE);
Please refer to above meme

2023-02-04 13:47 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/subsystems/ArmSecondJoint.java
> +    public void configureDashboard() {
add speed

2023-02-05 14:20 UTC, merged