created Gripper
Spikes-2212-Programming-Guild/ChargedUp2023 pull request #6
Opened 2023-01-26 18:46 UTC by Spikes-2212

2023-01-27 09:52 UTC, OfriRosenbaum requested changes
Make this compile

2023-01-27 09:52 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Gripper.java
> +    public static Gripper getInstance() {
move this to be above the constructor

2023-01-27 10:02 UTC, OfriRosenbaum requested changes

2023-01-27 10:02 UTC, OfriRosenbaum commented on src/main/java/frc/robot/subsystems/Gripper.java
> +        this.solenoid = solenoid;
add a call to configureDashboard in the end of the constructor

2023-02-04 08:24 UTC, Yoel-Perman-Brilliant requested changes

2023-02-04 08:24 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/CloseGripper.java
> +        gripper.closeGripper();
why is this in the constructor?

2023-02-04 08:24 UTC, Yoel-Perman-Brilliant commented on src/main/java/frc/robot/commands/OpenGripper.java
> +        gripper.openGripper();
why is this in the constructor?

2023-02-04 09:12 UTC, OfriRosenbaum approved these changes

2023-02-04 13:27 UTC, Yoel-Perman-Brilliant approved these changes

2023-02-04 15:59 UTC, merged